const randomParagraph = (difficulty) => {
  return paraArr[Math.floor(Math.random() * paraArr.length)];
  // return paraArr[0];
};



const paraArr = [
  "A Merchant travelling into a foreign Country, fell extreamly in Love with a young Lady; but being a stranger in that Nation, and beneath her, both in Birth and Wealth, he could have but little hopes of obtaining his desire; however his Love growing more and more vehement upon him, even to the slighting of all difficulties, he resolved at last to Steal her away; which he had the better opportunity to do, because her Father's house was not far from the Sea, and she often using to gather shells upon the shore accompanied not with above two to three of her servants it encouraged him the more to execute his design. Thus coming one time with a little leight Vessel, not unlike a Packet-boat, mann'd with some few Sea-men, and well victualled, for fear of some accidents, which might perhaps retard their journey, to the place where she used to repair; he forced her away: But when he fancied himself the happiest man of the World, he proved to be the most unfortunate; for Heaven frowning at his Theft, raised such a Tempest, as they knew not what to do, or whither to steer their course; so that the Vessel, both by its own leightness, and the violent motion of the Wind, was carried as swift as an Arrow out of a Bow, towards the North-pole, and in a short time reached the Icy Sea, where the wind forced it amongst huge pieces of Ice; but being little, and leight, it did by the assistance and favour of the gods to this virtuous Lady, so turn and wind through those precipices, as if it had been guided by some experienced Pilot, and skilful Mariner: But alas! ",
  "The book's protagonist is an amateur inventor or scientist living in London who is never named; he is identified simply as The Time Traveller. Having demonstrated to friends using a miniature model that time is a fourth dimension, and that a suitable apparatus can move back and forth in this fourth dimension, he builds a full-scale model capable of carrying himself. He sets off on a journey into the future.",
  "I found a little crowd of perhaps twenty people surrounding the huge hole in which the cylinder lay. I have already described the appearance of that colossal bulk, embedded in the ground. The turf and gravel about it seemed charred as if by a sudden explosion. No doubt its impact had caused a flash of fire. Henderson and Ogilvy were not there. I think they perceived that nothing was to be done for the present, and had gone away to breakfast at Henderson’s house.There were four or five boys sitting on the edge of the Pit, with their feet dangling, and amusing themselves—until I stopped them—by throwing stones at the giant mass. After I had spoken to them about it, they began playing at “touch” in and out of the group of bystanders.Among these were a couple of cyclists, a jobbing gardener I employed sometimes, a girl carrying a baby, Gregg the butcher and his little boy, and two or three loafers and golf caddies who were accustomed to hang about the railway station. There was very little talking. Few of the common people in England had anything but the vaguest astronomical ideas in those days. Most of them were staring quietly at the big table like end of the cylinder, which was still as Ogilvy and Henderson had left it. I fancy the popular expectation of a heap of charred corpses was disappointed at this inanimate bulk. Some went away while I was there, and other people came. I clambered into the pit and fancied I heard a faint movement under my feet. The top had certainly ceased to rotate.It was only when I got thus close to it that the strangeness of this object was at all evident to me. At the first glance it was really no more exciting than an overturned carriage or a tree blown across the road. Not so much so, indeed. It looked like a rusty gas float. It required a certain amount of scientific education to perceive that the grey scale of the Thing was no common oxide, that the yellowish-white metal that gleamed in the crack between the lid and the cylinder had an unfamiliar hue. “Extra-terrestrial” had no meaning for most of the onlookers.At that time it was quite clear in my own mind that the Thing had come from the planet Mars, but I judged it improbable that it contained any living creature. I thought the unscrewing might be automatic. In spite of Ogilvy, I still believed that there were men in Mars. My mind ran fancifully on the possibilities of its containing manuscript, on the difficulties in translation that might arise, whether we should find coins and models in it, and so forth. Yet it was a little too large for assurance on this idea. I felt an impatience to see it opened. About eleven, as nothing seemed happening, I walked back, full of such thought, to my home in Maybury. But I found it difficult to get to work upon my abstract investigations.In the afternoon the appearance of the common had altered very much. The early editions of the evening papers had startled London with enormous headlines."
];

export default randomParagraph;
 